spring.application.name=service-b
server.port=8082
service.c.url=http://localhost:8083/api/process
# 线程池配置
thread.pool.core-size=20
thread.pool.max-size=20
thread.pool.queue-capacity=200
thread.pool.keep-alive-seconds=60